apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-app-configmap
  namespace: strapi
data:
  HOST: 0.0.0.0
  PORT: "1337"
  DATABASE_CLIENT: mysql
  DATABASE_HOST: strapi-db
  DATABASE_PORT: "3306"
  DATABASE_NAME: strapi-db
  DATABASE_USERNAME: admin
  NODE_ENV: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-db-configmap
  namespace: strapi
data:
  MARIADB_USER: admin
  MARIADB_DATABASE: strapi-db
